### ISSUE TITLE
Update HF model cards to refer to LREC paper

### ISSUE THREAD

**Issue by jowagner** [jbrry/Irish-BERT#123]
The model cards for our bert and 2 gaelectra models on huggingface still point to (and provide bibtext for) our arxiv pre-print. Update to point to https://aclanthology.org/2022.lrec-1.511/ and current bibtex. Can only James do this or do we have a way to update stuff under "DCU-NLP" on HF?

**Comment by jbrry** [comment]
Done!

Regarding the HF account, I will pass on the login details.
