### ISSUE TITLE
Release of the Cloze Test set?

### ISSUE THREAD

**Issue by KhanhTungTran** [jbrry/Irish-BERT#125]
Hello,

Thank you for the great work! 

I am a PhD student in AI at University College Cork, and I am interested in training large-scale language models for Irish.

I am wondering if you can release the Cloze Test set used in your paper? It will be a great resource for evaluation of Irish-based language models.

Thank you.

**Comment by laurenCassidy** [comment]
Hi @KhanhTungTran,
Here is the corpus used for the cloze test:
[cloze.csv](https://github.com/jbrry/Irish-BERT/files/14480149/cloze.csv)

**Comment by laurenCassidy** [comment]
@jbrry will I add the cloze test script to the repository or share it another way? GitHub doesn't allow me to attact .py file to comment

**Comment by KhanhTungTran** [comment]
Thank you for the corpus file!

**Comment by laurenCassidy** [comment]
I have added the cloze.py script to the scripts directory

**Comment by KhanhTungTran** [comment]
Hi guys,

Just want to let you know that we have published our articles on building Irish-based LLMs, where your Cloze Test set was an important resource for evaluation.

As our models are causal language model, we have to redo the evaluation method to fit with causal LM instead of masked LM. However, our best accuracy was 0.80, approximately that of your gaBert model, indicating that more can be done to develop a proficient Irish language model.

[1] Tran, K. T., O'Sullivan, B., & Nguyen, H. D. UCCIX: Irish-eXcellence Large Language Model (2024). In ECAI2024 - Demo Track.
[2] Tran, K.T., O'Sullivan, B. and Nguyen, H.D. Irish-based Large Language Model with extreme low-resource settings in machine translation (2024). In LoResMT2024, ACL.
